sonar.projectKey=DiFF
sonar.projectName=DiFF
sonar.projectVersion=1.0

sonar.sources=src,client,python,app
sonar.inclusions=**/*.java,**/*.js,**/*.py
sonar.java.binaries=target/classes
sonar.java.source=17

sonar.host.url=http://localhost:9000
sonar.login=sqa_c8804d52053e4cbfe7b75640bfb9a9465c75b60d

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.cpd.exclusions=
sonar.cpd.analysis=true
