sonar.projectKey=DiFF
sonar.projectName=DiFF
sonar.projectVersion=1.0

sonar.sources=src,client,python,app
sonar.inclusions=**/*.java,**/*.js,**/*.py
sonar.java.binaries=target/classes
sonar.java.source=17

sonar.host.url=http://localhost:9000
sonar.login=sqa_7d73ebaedd5349b0815f0e321ac2fdf48488801b

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.cpd.exclusions=
sonar.cpd.analysis=true
