sonar.projectKey=DiFF
sonar.projectName=DiFF
sonar.projectVersion=1.0

sonar.sources=src,client,python,app
sonar.inclusions=**/*.java,**/*.js,**/*.py
sonar.java.binaries=target/classes
sonar.java.source=17

sonar.host.url=http://localhost:9000
sonar.login=sqa_57f3e301d3a26fe6bc68781ae4b1f38bddd379d1

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.binaries=target/classes,build/classes/java/main

sonar.cpd.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/target/**,**/.venv/**,**/venv/**
sonar.cpd.analysis=true
